package srtapi

// #cgo LDFLAGS: -lsrt
// #include <srt/srt.h>
import "C"
import (
	"syscall"
	"unsafe"
)

type _Socklen C.int

var rsa syscall.RawSockaddrAny
var rs4 syscall.RawSockaddrInet4
var rs6 syscall.RawSockaddrInet6

const (
	SizeofSockaddrAny   = _Socklen(unsafe.Sizeof(rsa))
	SizeofSockaddrInet4 = _Socklen(unsafe.Sizeof(rs4))
	SizeofSockaddrInet6 = _Socklen(unsafe.Sizeof(rs6))
)

// SRT socket status
const (
	SRTS_INIT       = C.SRTS_INIT
	SRTS_OPENED     = C.SRTS_OPENED
	SRTS_LISTENING  = C.SRTS_LISTENING
	SRTS_CONNECTING = C.SRTS_CONNECTING
	SRTS_CONNECTED  = C.SRTS_CONNECTED
	SRTS_BROKEN     = C.SRTS_BROKEN
	SRTS_CLOSING    = C.SRTS_CLOSING
	SRTS_CLOSED     = C.SRTS_CLOSED
	SRTS_NONEXIST   = C.SRTS_NONEXIST
)

// SRT socket options
const (
	SRTO_MSS            = C.SRTO_MSS
	SRTO_SNDSYN         = C.SRTO_SNDSYN
	SRTO_RCVSYN         = C.SRTO_RCVSYN
	SRTO_ISN            = C.SRTO_ISN
	SRTO_FC             = C.SRTO_FC
	SRTO_SNDBUF         = C.SRTO_SNDBUF
	SRTO_RCVBUF         = C.SRTO_RCVBUF
	SRTO_LINGER         = C.SRTO_LINGER
	SRTO_UDP_SNDBUF     = C.SRTO_UDP_SNDBUF
	SRTO_UDP_RCVBUF     = C.SRTO_UDP_RCVBUF
	SRTO_RENDEZVOUS     = C.SRTO_RENDEZVOUS
	SRTO_SNDTIMEO       = C.SRTO_SNDTIMEO
	SRTO_RCVTIMEO       = C.SRTO_RCVTIMEO
	SRTO_REUSEADDR      = C.SRTO_REUSEADDR
	SRTO_MAXBW          = C.SRTO_MAXBW
	SRTO_STATE          = C.SRTO_STATE
	SRTO_EVENT          = C.SRTO_EVENT
	SRTO_SNDDATA        = C.SRTO_SNDDATA
	SRTO_RCVDATA        = C.SRTO_RCVDATA
	SRTO_SENDER         = C.SRTO_SENDER
	SRTO_TSBPDMODE      = C.SRTO_TSBPDMODE
	SRTO_LATENCY        = C.SRTO_LATENCY
	SRTO_TSBPDDELAY     = C.SRTO_TSBPDDELAY
	SRTO_INPUTBW        = C.SRTO_INPUTBW
	SRTO_OHEADBW        = C.SRTO_OHEADBW
	SRTO_PASSPHRASE     = C.SRTO_PASSPHRASE
	SRTO_PBKEYLEN       = C.SRTO_PBKEYLEN
	SRTO_KMSTATE        = C.SRTO_KMSTATE
	SRTO_IPTTL          = C.SRTO_IPTTL
	SRTO_IPTOS          = C.SRTO_IPTOS
	SRTO_TLPKTDROP      = C.SRTO_TLPKTDROP
	SRTO_NAKREPORT      = C.SRTO_NAKREPORT
	SRTO_VERSION        = C.SRTO_VERSION
	SRTO_PEERVERSION    = C.SRTO_PEERVERSION
	SRTO_CONNTIMEO      = C.SRTO_CONNTIMEO
	SRTO_SNDPEERKMSTATE = C.SRTO_SNDPEERKMSTATE
	SRTO_RCVKMSTATE     = C.SRTO_RCVKMSTATE
	SRTO_LOSSMAXTTL     = C.SRTO_LOSSMAXTTL
	SRTO_RCVLATENCY     = C.SRTO_RCVLATENCY
	SRTO_PEERLATENCY    = C.SRTO_PEERLATENCY
	SRTO_MINVERSION     = C.SRTO_MINVERSION
	SRTO_STREAMID       = C.SRTO_STREAMID
	SRTO_SMOOTHER       = C.SRTO_SMOOTHER
	SRTO_MESSAGEAPI     = C.SRTO_MESSAGEAPI
	SRTO_PAYLOADSIZE    = C.SRTO_PAYLOADSIZE
	SRTO_TRANSTYPE      = C.SRTO_TRANSTYPE
)

// SRT trans type
const (
	SRTT_LIVE    = C.SRTT_LIVE
	SRTT_FILE    = C.SRTT_FILE
	SRTT_INVALID = C.SRTT_INVALID
)

// SRT errno
const (
	SRT_EUNKNOWN        = C.SRT_EUNKNOWN
	SRT_SUCCESS         = C.SRT_SUCCESS
	SRT_ECONNSETUP      = C.SRT_ECONNSETUP
	SRT_ENOSERVER       = C.SRT_ENOSERVER
	SRT_ECONNREJ        = C.SRT_ECONNREJ
	SRT_ESOCKFAIL       = C.SRT_ESOCKFAIL
	SRT_ESECFAIL        = C.SRT_ESECFAIL
	SRT_ECONNFAIL       = C.SRT_ECONNFAIL
	SRT_ECONNLOST       = C.SRT_ECONNLOST
	SRT_ENOCONN         = C.SRT_ENOCONN
	SRT_ERESOURCE       = C.SRT_ERESOURCE
	SRT_ETHREAD         = C.SRT_ETHREAD
	SRT_ENOBUF          = C.SRT_ENOBUF
	SRT_EFILE           = C.SRT_EFILE
	SRT_EINVRDOFF       = C.SRT_EINVRDOFF
	SRT_ERDPERM         = C.SRT_ERDPERM
	SRT_EINVWROFF       = C.SRT_EINVWROFF
	SRT_EWRPERM         = C.SRT_EWRPERM
	SRT_EINVOP          = C.SRT_EINVOP
	SRT_EBOUNDSOCK      = C.SRT_EBOUNDSOCK
	SRT_ECONNSOCK       = C.SRT_ECONNSOCK
	SRT_EINVPARAM       = C.SRT_EINVPARAM
	SRT_EINVSOCK        = C.SRT_EINVSOCK
	SRT_EUNBOUNDSOCK    = C.SRT_EUNBOUNDSOCK
	SRT_ENOLISTEN       = C.SRT_ENOLISTEN
	SRT_ERDVNOSERV      = C.SRT_ERDVNOSERV
	SRT_ERDVUNBOUND     = C.SRT_ERDVUNBOUND
	SRT_EINVALMSGAPI    = C.SRT_EINVALMSGAPI
	SRT_EINVALBUFFERAPI = C.SRT_EINVALBUFFERAPI
	SRT_EDUPLISTEN      = C.SRT_EDUPLISTEN
	SRT_ELARGEMSG       = C.SRT_ELARGEMSG
	SRT_EINVPOLLID      = C.SRT_EINVPOLLID
	SRT_EASYNCFAIL      = C.SRT_EASYNCFAIL
	SRT_EASYNCSND       = C.SRT_EASYNCSND
	SRT_EASYNCRCV       = C.SRT_EASYNCRCV
	SRT_ETIMEOUT        = C.SRT_ETIMEOUT
	SRT_ECONGEST        = C.SRT_ECONGEST
	SRT_EPEERERR        = C.SRT_EPEERERR
)

// SRT log
const (
	SRT_LOGFA_GENERAL  = 0
	SRT_LOGFA_BSTATS   = 1
	SRT_LOGFA_CONTROL  = 2
	SRT_LOGFA_DATA     = 3
	SRT_LOGFA_TSBPD    = 4
	SRT_LOGFA_REXMIT   = 5
	SRT_LOGFA_LASTNONE = 31
)

// SRT epoll opt
const (
	SRT_EPOLL_IN  = C.SRT_EPOLL_IN
	SRT_EPOLL_OUT = C.SRT_EPOLL_OUT
	SRT_EPOLL_ERR = C.SRT_EPOLL_ERR
)

// SRT const
const (
	SRT_INVALID_SOCK = -1
	SRT_ERROR        = -1
)
